### ISSUE TITLE
Pool of senders

### ISSUE THREAD

**Issue by gabrielmocan** [questdb/go-questdb-client#11]
It would be nice to have something like https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool so we could instantiate a pool of senders to be concurrently reused across go routines.

**Comment by sklarsa** [comment]
FYI, we've changed the API slightly in this new commit. The pool is easier to use since you don't need to worry about explicitly releasing senders from the pool, you can just close them:

https://github.com/questdb/go-questdb-client/pull/53

**Comment by puzpuzpuz** [comment]
I've just published v3.2.0 with the pool API changes. The release notes include a code migration example: https://github.com/questdb/go-questdb-client/releases/tag/v3.2.0
