### ISSUE TITLE
Add support for explicit timestamp columns

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/go-questdb-client#2]
Currently you can send timestamps as `long` (int64), but this assumes a table was already pre-created. It wont work for auto-created table. It would be nice to support timestamp columns explicitly.

Java client counterpart PR: https://github.com/questdb/questdb/pull/2257

**Comment by jerrinot** [comment]
a community user stumbled upon this issue: https://questdb.slack.com/archives/C037Z3948KY/p1662321459645359
