### ISSUE TITLE
Now that Data Deduplication is available, make the LineSender safer

### ISSUE THREAD

**Issue by probably-not** [questdb/go-questdb-client#21]
There are several issues and pull requests throughout this repo that discuss the fact that the LineSender is not fully safe, i.e. there's issues in auto-reconnection, there's no way to retrieve the failed sent buffer to retry if there is a connection issue, etc.

@puzpuzpuz [has said that this can't be implemented without data deduplication on the server side](https://github.com/questdb/go-questdb-client/pull/18#discussion_r1246229904).

According to the QuestDB Docs site, data deduplication is implemented on the DB since QuestDB 7.3: https://questdb.io/docs/concept/deduplication/

Can we get this MAJOR ISSUE fixed (at the very least as an option on the client that we can enable) so we can have some better safety in what will happen if there's a connection issue, so we don't lose data and we don't have to implement reconnection logic on our own?

**Comment by probably-not** [comment]
@puzpuzpuz I agree that commit/error propagation is important, but adding a reconnect+resend of the current batch is something that can be added regardless of commit/error propagation. If there's a TCP write error or a broken pipe, the entire batch is lost on the client side, which is a pretty critical thing to lose, and it doesn't relate to propagating errors from the actual write itself, just to making sure that we don't lose data when there is a TCP error.

This feature can be added now, so that clients don't lose data due to TCP issues (regardless of database write issues).

**Comment by puzpuzpuz** [comment]
Closing this one since v3 shipped HTTP sender which allows explicit control over transactions and has automatic retry behavior.
