### ISSUE TITLE
Add support for Long256 type

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/go-questdb-client#3]
https://questdb.io/docs/reference/api/ilp/columnset-types#long256

**Comment by bluestreak01** [comment]
we should also add cases to test json

**Comment by JammUtkarsh** [comment]
Hey, if no one is working on it, then I would like to work on it!

**Comment by puzpuzpuz** [comment]
@JammUtkarsh that's great. Assigned you to this one. Thanks!
