### ISSUE TITLE
Support auto_flush_rows=off and auto_flush_interval=off config options

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/go-questdb-client#31]
See https://github.com/questdb/questdb/pull/4385/

**Comment by jammutkarsh** [comment]
Hey @puzpuzpuz,

From what I have understood, is [this](https://github.com/jammutkarsh/go-questdb-client/commit/ab45385682bc8aaf9420bffa0a1715889a82a68d) what needs to be added?

**Comment by puzpuzpuz** [comment]
@jammutkarsh pretty much. Also, some tests should be added for config parser and sender behavior with the new "off" values.
